[build]
  command = "yarn build"
  publish = "out"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[context.production.environment]
  NEXTAUTH_URL = "https://sp1-omni-notes.netlify.app"

[context.develop.environment]
  NEXTAUTH_URL = "https://develop--sp1-omni-notes.netlify.app"
